# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Final Homework/project_2/project_2.srcs/sources_1/ip/mult_demod/mult_demod.xci
# IP: The module: 'mult_demod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Final Homework/project_2/project_2.gen/sources_1/ip/mult_demod/mult_demod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_demod'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Final Homework/project_2/project_2.srcs/sources_1/ip/mult_demod/mult_demod.xci
# IP: The module: 'mult_demod' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Final Homework/project_2/project_2.gen/sources_1/ip/mult_demod/mult_demod_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_demod'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
