# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Final Homework/project_2/project_2.srcs/sources_1/ip/dds_demod_cos/dds_demod_cos.xci
# IP: The module: 'dds_demod_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Final Homework/project_2/project_2.gen/sources_1/ip/dds_demod_cos/dds_demod_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_demod_cos'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Final Homework/project_2/project_2.srcs/sources_1/ip/dds_demod_cos/dds_demod_cos.xci
# IP: The module: 'dds_demod_cos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Final Homework/project_2/project_2.gen/sources_1/ip/dds_demod_cos/dds_demod_cos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_demod_cos'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
