# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/course design/final/project_1/project_1.srcs/sources_1/ip/clock128M/clock128M.xci
# IP: The module: 'clock128M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/course design/final/project_1/project_1.srcs/sources_1/ip/clock128M/clock128M.xci
# IP: The module: 'clock128M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/course design/final/project_1/project_1.gen/sources_1/ip/clock128M/clock128M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock128M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
